version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    labels:
      webapp: "varlogs"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9090:3000"
    environment:
      - GF_USERS_DEFAULT_UI_THEME=light
      - "GF_SERVER_CUSTOM_RESPONSE_HEADERS=myHeader:User is: ${nameOfGrafanaUser}. Host is: ${nameOfGrafanaHost}."
    depends_on:
      - loki